// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: meta_message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IncrementOrderBookInfo 表示增量订单簿信息
type MetaMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Magic   uint32 `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Type    int64  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 消息类型
	Size    uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"` // 消息大小
	Code    uint64 `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Data    []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *MetaMessage) Reset() {
	*x = MetaMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaMessage) ProtoMessage() {}

func (x *MetaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_meta_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaMessage.ProtoReflect.Descriptor instead.
func (*MetaMessage) Descriptor() ([]byte, []int) {
	return file_meta_message_proto_rawDescGZIP(), []int{0}
}

func (x *MetaMessage) GetMagic() uint32 {
	if x != nil {
		return x.Magic
	}
	return 0
}

func (x *MetaMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MetaMessage) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MetaMessage) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MetaMessage) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MetaMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // 用户名
	Rands  []byte `protobuf:"bytes,2,opt,name=rands,proto3" json:"rands,omitempty"`
	Digest []byte `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *UserAuth) Reset() {
	*x = UserAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuth) ProtoMessage() {}

func (x *UserAuth) ProtoReflect() protoreflect.Message {
	mi := &file_meta_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuth.ProtoReflect.Descriptor instead.
func (*UserAuth) Descriptor() ([]byte, []int) {
	return file_meta_message_proto_rawDescGZIP(), []int{1}
}

func (x *UserAuth) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *UserAuth) GetRands() []byte {
	if x != nil {
		return x.Rands
	}
	return nil
}

func (x *UserAuth) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"` // 操作名称
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_meta_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_meta_message_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Result) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Result) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Result) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type QuoteStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // 开始时间 utc timestamp, 0 : 从最新的行情开始
	End   int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`     // 结束时间，并不包含
}

func (x *QuoteStart) Reset() {
	*x = QuoteStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteStart) ProtoMessage() {}

func (x *QuoteStart) ProtoReflect() protoreflect.Message {
	mi := &file_meta_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteStart.ProtoReflect.Descriptor instead.
func (*QuoteStart) Descriptor() ([]byte, []int) {
	return file_meta_message_proto_rawDescGZIP(), []int{3}
}

func (x *QuoteStart) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *QuoteStart) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type QuoteSeek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // 开始时间 utc timestamp, 0 : 从最新的行情开始
}

func (x *QuoteSeek) Reset() {
	*x = QuoteSeek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_meta_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteSeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteSeek) ProtoMessage() {}

func (x *QuoteSeek) ProtoReflect() protoreflect.Message {
	mi := &file_meta_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteSeek.ProtoReflect.Descriptor instead.
func (*QuoteSeek) Descriptor() ([]byte, []int) {
	return file_meta_message_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteSeek) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

var File_meta_message_proto protoreflect.FileDescriptor

var file_meta_message_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x8d, 0x01,
	0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61,
	0x67, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4c, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x61,
	0x6e, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x0a, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22,
	0x21, 0x0a, 0x09, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x53, 0x65, 0x65, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_meta_message_proto_rawDescOnce sync.Once
	file_meta_message_proto_rawDescData = file_meta_message_proto_rawDesc
)

func file_meta_message_proto_rawDescGZIP() []byte {
	file_meta_message_proto_rawDescOnce.Do(func() {
		file_meta_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_meta_message_proto_rawDescData)
	})
	return file_meta_message_proto_rawDescData
}

var file_meta_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_meta_message_proto_goTypes = []any{
	(*MetaMessage)(nil), // 0: message.MetaMessage
	(*UserAuth)(nil),    // 1: message.UserAuth
	(*Result)(nil),      // 2: message.Result
	(*QuoteStart)(nil),  // 3: message.QuoteStart
	(*QuoteSeek)(nil),   // 4: message.QuoteSeek
}
var file_meta_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meta_message_proto_init() }
func file_meta_message_proto_init() {
	if File_meta_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_meta_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MetaMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UserAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_message_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_message_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*QuoteStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_meta_message_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*QuoteSeek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_meta_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_message_proto_goTypes,
		DependencyIndexes: file_meta_message_proto_depIdxs,
		MessageInfos:      file_meta_message_proto_msgTypes,
	}.Build()
	File_meta_message_proto = out.File
	file_meta_message_proto_rawDesc = nil
	file_meta_message_proto_goTypes = nil
	file_meta_message_proto_depIdxs = nil
}
