// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: quote_period.proto

// update 0.2 2024.08.30

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IncrementOrderBookInfo 表示增量订单簿信息
type IncrementOrderBookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp        int64         `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                           // 时间戳，表示该信息的事件时间
	TransTs          int64         `protobuf:"varint,2,opt,name=trans_ts,json=transTs,proto3" json:"trans_ts,omitempty"`                                // 交易时间戳
	FirstUpdateId    int64         `protobuf:"varint,3,opt,name=first_update_id,json=firstUpdateId,proto3" json:"first_update_id,omitempty"`            // 第一个更新的订单簿ID
	LastUpdateId     int64         `protobuf:"varint,4,opt,name=last_update_id,json=lastUpdateId,proto3" json:"last_update_id,omitempty"`               // 最后更新的订单簿ID
	PrevLastUpdateId int64         `protobuf:"varint,5,opt,name=prev_last_update_id,json=prevLastUpdateId,proto3" json:"prev_last_update_id,omitempty"` // 上一个订单簿ID
	Bids             []*PriceLevel `protobuf:"bytes,6,rep,name=bids,proto3" json:"bids,omitempty"`                                                      // 买单列表
	Asks             []*PriceLevel `protobuf:"bytes,7,rep,name=asks,proto3" json:"asks,omitempty"`                                                      // 卖单列表
}

func (x *IncrementOrderBookInfo) Reset() {
	*x = IncrementOrderBookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_period_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementOrderBookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementOrderBookInfo) ProtoMessage() {}

func (x *IncrementOrderBookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quote_period_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementOrderBookInfo.ProtoReflect.Descriptor instead.
func (*IncrementOrderBookInfo) Descriptor() ([]byte, []int) {
	return file_quote_period_proto_rawDescGZIP(), []int{0}
}

func (x *IncrementOrderBookInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IncrementOrderBookInfo) GetTransTs() int64 {
	if x != nil {
		return x.TransTs
	}
	return 0
}

func (x *IncrementOrderBookInfo) GetFirstUpdateId() int64 {
	if x != nil {
		return x.FirstUpdateId
	}
	return 0
}

func (x *IncrementOrderBookInfo) GetLastUpdateId() int64 {
	if x != nil {
		return x.LastUpdateId
	}
	return 0
}

func (x *IncrementOrderBookInfo) GetPrevLastUpdateId() int64 {
	if x != nil {
		return x.PrevLastUpdateId
	}
	return 0
}

func (x *IncrementOrderBookInfo) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *IncrementOrderBookInfo) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// TradeInfo 表示交易信息
type TradeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     int64   `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                // 时间戳，表示交易发生的时间
	TradeId       int64   `protobuf:"varint,2,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                     // 交易ID
	Price         float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`                                       // 交易价格
	Qty           float64 `protobuf:"fixed64,4,opt,name=qty,proto3" json:"qty,omitempty"`                                           // 交易数量
	BuyerOrderId  int64   `protobuf:"varint,5,opt,name=buyer_order_id,json=buyerOrderId,proto3" json:"buyer_order_id,omitempty"`    // 买方订单ID
	SellerOrderId int64   `protobuf:"varint,6,opt,name=seller_order_id,json=sellerOrderId,proto3" json:"seller_order_id,omitempty"` // 卖方订单ID
	TradeTs       int64   `protobuf:"varint,7,opt,name=trade_ts,json=tradeTs,proto3" json:"trade_ts,omitempty"`                     // 交易时间戳
	IsBuyerMaker  bool    `protobuf:"varint,8,opt,name=is_buyer_maker,json=isBuyerMaker,proto3" json:"is_buyer_maker,omitempty"`    // 买方是否是maker
	PlaceHolder   bool    `protobuf:"varint,9,opt,name=place_holder,json=placeHolder,proto3" json:"place_holder,omitempty"`         // 占位符
}

func (x *TradeInfo) Reset() {
	*x = TradeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_period_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeInfo) ProtoMessage() {}

func (x *TradeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quote_period_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeInfo.ProtoReflect.Descriptor instead.
func (*TradeInfo) Descriptor() ([]byte, []int) {
	return file_quote_period_proto_rawDescGZIP(), []int{1}
}

func (x *TradeInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TradeInfo) GetTradeId() int64 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

func (x *TradeInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeInfo) GetQty() float64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *TradeInfo) GetBuyerOrderId() int64 {
	if x != nil {
		return x.BuyerOrderId
	}
	return 0
}

func (x *TradeInfo) GetSellerOrderId() int64 {
	if x != nil {
		return x.SellerOrderId
	}
	return 0
}

func (x *TradeInfo) GetTradeTs() int64 {
	if x != nil {
		return x.TradeTs
	}
	return 0
}

func (x *TradeInfo) GetIsBuyerMaker() bool {
	if x != nil {
		return x.IsBuyerMaker
	}
	return false
}

func (x *TradeInfo) GetPlaceHolder() bool {
	if x != nil {
		return x.PlaceHolder
	}
	return false
}

// PriceLevel 表示价格和数量
type PriceLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  float64 `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`   // 价格
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"` // 数量
}

func (x *PriceLevel) Reset() {
	*x = PriceLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_period_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceLevel) ProtoMessage() {}

func (x *PriceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_quote_period_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceLevel.ProtoReflect.Descriptor instead.
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return file_quote_period_proto_rawDescGZIP(), []int{2}
}

func (x *PriceLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceLevel) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// SnapShotInfo 表示订单簿的快照信息
type SnapShotInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastUpdateId int64         `protobuf:"varint,1,opt,name=last_update_id,json=lastUpdateId,proto3" json:"last_update_id,omitempty"` // 最后更新的订单簿ID
	Timestamp    int64         `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳，表示该信息的事件时间
	TradeTs      int64         `protobuf:"varint,3,opt,name=trade_ts,json=tradeTs,proto3" json:"trade_ts,omitempty"`                  // 交易时间戳
	Bids         []*PriceLevel `protobuf:"bytes,4,rep,name=bids,proto3" json:"bids,omitempty"`                                        // 买单列表
	Asks         []*PriceLevel `protobuf:"bytes,5,rep,name=asks,proto3" json:"asks,omitempty"`                                        // 卖单列表
}

func (x *SnapShotInfo) Reset() {
	*x = SnapShotInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_period_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapShotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapShotInfo) ProtoMessage() {}

func (x *SnapShotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quote_period_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapShotInfo.ProtoReflect.Descriptor instead.
func (*SnapShotInfo) Descriptor() ([]byte, []int) {
	return file_quote_period_proto_rawDescGZIP(), []int{3}
}

func (x *SnapShotInfo) GetLastUpdateId() int64 {
	if x != nil {
		return x.LastUpdateId
	}
	return 0
}

func (x *SnapShotInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SnapShotInfo) GetTradeTs() int64 {
	if x != nil {
		return x.TradeTs
	}
	return 0
}

func (x *SnapShotInfo) GetBids() []*PriceLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *SnapShotInfo) GetAsks() []*PriceLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// SymbolInfo 表示某个交易对的信息
type SymbolInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string                    `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // 交易对符号，例如 "BTCUSDT"
	Trades []*TradeInfo              `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"` // 该交易对的交易信息列表
	Incs   []*IncrementOrderBookInfo `protobuf:"bytes,3,rep,name=incs,proto3" json:"incs,omitempty"`     // 该交易对的增量订单簿信息列表
	Snaps  []*SnapShotInfo           `protobuf:"bytes,4,rep,name=snaps,proto3" json:"snaps,omitempty"`   // 该交易对的快照信息
}

func (x *SymbolInfo) Reset() {
	*x = SymbolInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_period_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymbolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolInfo) ProtoMessage() {}

func (x *SymbolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quote_period_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolInfo.ProtoReflect.Descriptor instead.
func (*SymbolInfo) Descriptor() ([]byte, []int) {
	return file_quote_period_proto_rawDescGZIP(), []int{4}
}

func (x *SymbolInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolInfo) GetTrades() []*TradeInfo {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *SymbolInfo) GetIncs() []*IncrementOrderBookInfo {
	if x != nil {
		return x.Incs
	}
	return nil
}

func (x *SymbolInfo) GetSnaps() []*SnapShotInfo {
	if x != nil {
		return x.Snaps
	}
	return nil
}

// PeriodMessage 表示一个3s时间段内的市场数据汇总
type PeriodMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Period      int64         `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`                             // 数据所属的时间段,period 3s一次
	Ts          int64         `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`                                     // 消息生成的时间戳
	PostTs      int64         `protobuf:"varint,3,opt,name=post_ts,json=postTs,proto3" json:"post_ts,omitempty"`               // 消息发布到kafka的时间戳
	PosterId    string        `protobuf:"bytes,4,opt,name=poster_id,json=posterId,proto3" json:"poster_id,omitempty"`          // 发布者服务的唯一标识符
	SymbolInfos []*SymbolInfo `protobuf:"bytes,5,rep,name=symbol_infos,json=symbolInfos,proto3" json:"symbol_infos,omitempty"` // 包含多个交易对信息的列表
}

func (x *PeriodMessage) Reset() {
	*x = PeriodMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quote_period_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeriodMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodMessage) ProtoMessage() {}

func (x *PeriodMessage) ProtoReflect() protoreflect.Message {
	mi := &file_quote_period_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodMessage.ProtoReflect.Descriptor instead.
func (*PeriodMessage) Descriptor() ([]byte, []int) {
	return file_quote_period_proto_rawDescGZIP(), []int{5}
}

func (x *PeriodMessage) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *PeriodMessage) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *PeriodMessage) GetPostTs() int64 {
	if x != nil {
		return x.PostTs
	}
	return 0
}

func (x *PeriodMessage) GetPosterId() string {
	if x != nil {
		return x.PosterId
	}
	return ""
}

func (x *PeriodMessage) GetSymbolInfos() []*SymbolInfo {
	if x != nil {
		return x.SymbolInfos
	}
	return nil
}

var File_quote_period_proto protoreflect.FileDescriptor

var file_quote_period_proto_rawDesc = []byte{
	0x0a, 0x12, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa0, 0x02,
	0x0a, 0x16, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x5f,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x54,
	0x73, 0x12, 0x26, 0x0a, 0x0f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x2d, 0x0a, 0x13, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x70, 0x72,
	0x65, 0x76, 0x4c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x27,
	0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73,
	0x22, 0x9e, 0x02, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x71, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12,
	0x24, 0x0a, 0x0e, 0x62, 0x75, 0x79, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x62, 0x75, 0x79, 0x65, 0x72, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x54, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x73, 0x5f, 0x62,
	0x75, 0x79, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x69, 0x73, 0x42, 0x75, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x6b, 0x65, 0x72, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x48, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x22, 0x3a, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xbf, 0x01,
	0x0a, 0x0c, 0x53, 0x6e, 0x61, 0x70, 0x53, 0x68, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24,
	0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x54, 0x73, 0x12, 0x27, 0x0a,
	0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x22,
	0xb2, 0x01, 0x0a, 0x0a, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x2a, 0x0a, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x69, 0x6e, 0x63, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x63, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x6e, 0x61, 0x70, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x6e, 0x61, 0x70, 0x53, 0x68, 0x6f, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x73,
	0x6e, 0x61, 0x70, 0x73, 0x22, 0xa5, 0x01, 0x0a, 0x0d, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x0c, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x42, 0x14, 0x5a, 0x12,
	0x2e, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quote_period_proto_rawDescOnce sync.Once
	file_quote_period_proto_rawDescData = file_quote_period_proto_rawDesc
)

func file_quote_period_proto_rawDescGZIP() []byte {
	file_quote_period_proto_rawDescOnce.Do(func() {
		file_quote_period_proto_rawDescData = protoimpl.X.CompressGZIP(file_quote_period_proto_rawDescData)
	})
	return file_quote_period_proto_rawDescData
}

var file_quote_period_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quote_period_proto_goTypes = []any{
	(*IncrementOrderBookInfo)(nil), // 0: message.IncrementOrderBookInfo
	(*TradeInfo)(nil),              // 1: message.TradeInfo
	(*PriceLevel)(nil),             // 2: message.PriceLevel
	(*SnapShotInfo)(nil),           // 3: message.SnapShotInfo
	(*SymbolInfo)(nil),             // 4: message.SymbolInfo
	(*PeriodMessage)(nil),          // 5: message.PeriodMessage
}
var file_quote_period_proto_depIdxs = []int32{
	2, // 0: message.IncrementOrderBookInfo.bids:type_name -> message.PriceLevel
	2, // 1: message.IncrementOrderBookInfo.asks:type_name -> message.PriceLevel
	2, // 2: message.SnapShotInfo.bids:type_name -> message.PriceLevel
	2, // 3: message.SnapShotInfo.asks:type_name -> message.PriceLevel
	1, // 4: message.SymbolInfo.trades:type_name -> message.TradeInfo
	0, // 5: message.SymbolInfo.incs:type_name -> message.IncrementOrderBookInfo
	3, // 6: message.SymbolInfo.snaps:type_name -> message.SnapShotInfo
	4, // 7: message.PeriodMessage.symbol_infos:type_name -> message.SymbolInfo
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_quote_period_proto_init() }
func file_quote_period_proto_init() {
	if File_quote_period_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quote_period_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*IncrementOrderBookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_period_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TradeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_period_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PriceLevel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_period_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SnapShotInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_period_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SymbolInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quote_period_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PeriodMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quote_period_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quote_period_proto_goTypes,
		DependencyIndexes: file_quote_period_proto_depIdxs,
		MessageInfos:      file_quote_period_proto_msgTypes,
	}.Build()
	File_quote_period_proto = out.File
	file_quote_period_proto_rawDesc = nil
	file_quote_period_proto_goTypes = nil
	file_quote_period_proto_depIdxs = nil
}
