# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meta_message.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'meta_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12meta_message.proto\x12\x07message\"e\n\x0bMetaMessage\x12\r\n\x05magic\x18\x01 \x01(\r\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0c\n\x04type\x18\x03 \x01(\x03\x12\x0c\n\x04size\x18\x04 \x01(\r\x12\x0c\n\x04\x63ode\x18\x05 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\"7\n\x08UserAuth\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05rands\x18\x02 \x01(\x0c\x12\x0e\n\x06\x64igest\x18\x03 \x01(\x0c\"B\n\x06Result\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\"(\n\nQuoteStart\x12\r\n\x05start\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\"\x1a\n\tQuoteSeek\x12\r\n\x05start\x18\x01 \x01(\x03\x42\x14Z\x12../message;messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meta_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022../message;message'
  _globals['_METAMESSAGE']._serialized_start=31
  _globals['_METAMESSAGE']._serialized_end=132
  _globals['_USERAUTH']._serialized_start=134
  _globals['_USERAUTH']._serialized_end=189
  _globals['_RESULT']._serialized_start=191
  _globals['_RESULT']._serialized_end=257
  _globals['_QUOTESTART']._serialized_start=259
  _globals['_QUOTESTART']._serialized_end=299
  _globals['_QUOTESEEK']._serialized_start=301
  _globals['_QUOTESEEK']._serialized_end=327
# @@protoc_insertion_point(module_scope)
