# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quote_common.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'quote_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quote_period_pb2 as quote__period__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10quote_recv.proto\x12\x07message\x1a\x12quote_period.proto\"\xc4\x01\n\tDepthInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08trans_ts\x18\x02 \x01(\x03\x12\x17\n\x0f\x66irst_update_id\x18\x03 \x01(\x03\x12\x16\n\x0elast_update_id\x18\x04 \x01(\x03\x12\x1b\n\x13prev_last_update_id\x18\x05 \x01(\x03\x12!\n\x04\x62ids\x18\x06 \x03(\x0b\x32\x13.message.PriceLevel\x12!\n\x04\x61sks\x18\x07 \x03(\x0b\x32\x13.message.PriceLevelB\x14Z\x12../message;messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quote_recv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022../message;message'
  _globals['_DEPTHINFO']._serialized_start=50
  _globals['_DEPTHINFO']._serialized_end=246
# @@protoc_insertion_point(module_scope)
